package io.bookflight.events;

import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationListener;
import org.springframework.stereotype.Component;

@Component
@Slf4j
public class ProduceKafkaEventListener implements ApplicationListener<ProduceKafkaEvent> {
    @Override
    public void onApplicationEvent(ProduceKafkaEvent event) {
        log.info("listening event generated by kafka {} ",event.getUserInfo());
        // here we will be calling kafka produce method to produce a data in kafka topic
    }
}
